import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react";
import './globals.css'
import Provider from '@/context/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shop 8',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Provider>
        <body className={inter.className} suppressHydrationWarning={true}>
          {children}
        </body>
      </Provider>

    </html>
  )
}
